/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haarfilterhorizontal;

/**
 *
 * @author user
 */
public class Features {

    /**
     * The FeatureA function produces a sliding window and generates a position
     * to lay down the window for further calculations
     */
    public void FeatureA() {
        int imgH = 5;
        int imgW = 5;
        int count = 0;
        int[][] integralValues = new int[5][5];
        /**
         * Image area is a class to calculate the area of a certain window
         * generated by the i and j values in the following loop and sliding it
         * through each position of the array which will later be replaced by an
         * image to calculate its features
         */
        ImageArea imageArea = new ImageArea();

        int w = 2, h = 1;
        for (int i = 1; i <= (imgW / w); i++) {
            for (int j = 1; j <= (imgH / h); j++) {
                for (int x = 1; x <= (imgW - i * w + 1); x++) {
                    for (int y = 1; y <= imgH - j * h + 1; y++) {
                        /**
                         * CalculateArea gives the area of the selected window
                         * with reference to the integral image and drastically
                         * reduces the computation time
                         */
                        imageArea.CalculateArea(i, j, x, y, count);
                        count++;
                    }
                }

//            System.out.println("COUNT= " + count);
            }
        }
    }
}
